language: node_js
node_js:
  - "stable"

#needed for lwip
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
  - "artifacts -v || curl -sL https://raw.githubusercontent.com/meatballhat/artifacts/master/install | bash"
script:
  - npm run build
after_script:
  - ./build/travis-upload-artifacts.sh
